config/routes.rb
Rails.application.routes.draw do
  resources :agendamentos
  devise_for :admins
  get 'welcome/index'
  root 'welcome#index'
  resources :cadastros

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agendamento.rb
class Agendamento < ActiveRecord::Base
validates :Nome, presence: true, length: { maximum: 50 }  
end

app/models/cadastro.rb
class Cadastro < ActiveRecord::Base
	validates :nome, presence: true, length: { maximum: 50 } 
	before_save { self.email = email.downcase } 
	validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create}, uniqueness: {case_sensitive: false} 
	def self.search(palavra)
		where("nome like ?", "%#{palavra}%")
	end
end

app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  before_action :set_agendamento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /agendamentos
  # GET /agendamentos.json
  def index
    @agendamentos = Agendamento.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end

  # GET /agendamentos/1
  # GET /agendamentos/1.json
  def show
  end

  #GET /agendamentos/new
  def new
    @agendamento = Agendamento.new
  end

  # GET /agendamentos/1/edit
  def edit
  end

  # POST /agendamentos
  # POST /agendamentos.json
  def create
    @agendamento = Agendamento.new(agendamento_params)

    respond_to do |format|
      if @agendamento.save
        format.html { redirect_to @agendamento, notice: 'Agendamento foi criado com sucesso!' }
        format.json { render :show, status: :created, location: @agendamento }
      else
        format.html { render :new }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendamentos/1
  # PATCH/PUT /agendamentos/1.json
  def update
    respond_to do |format|
      if @agendamento.update(agendamento_params)
        format.html { redirect_to @agendamento, notice: 'Agendamento foi editado com sucesso!' }
        format.json { render :show, status: :ok, location: @agendamento }
      else
        format.html { render :edit }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendamentos/1
  # DELETE /agendamentos/1.json
  def destroy
    @agendamento.destroy
    respond_to do |format|
      format.html { redirect_to agendamentos_url, notice: 'Agendamento foi excluido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agendamento
      @agendamento = Agendamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agendamento_params
      params.require(:agendamento).permit(:Nome, :Descricao, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /cadastros
  # GET /cadastros.json
  def index
    if params[:search]
    @cadastros = Cadastro.search(params[:search])
   else
    @cadastros = Cadastro.all
 end
end
  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = Cadastro.new
  end

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = Cadastro.new(cadastro_params)

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to @cadastro, notice: 'Cadastro foi criado com sucesso!.' }
        format.json { render :show, status: :created, location: @cadastro }
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: 'Cadastro foi editado com sucesso!.' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Cadastro foi excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_params
      params.require(:cadastro).permit(:nome, :email, :telefone, :celular)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agendamentos/_form.html.erb
<%= form_for(@agendamento) do |f| %>
  <% if @agendamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agendamento.errors.count, "error") %> prohibited this agendamento from being saved:</h2>

      <ul>
      <% @agendamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nome %><br>
    <%= f.text_field :Nome %>
  </div>
  <div class="field">
    <%= f.label :Descrição %><br>
    <%= f.text_area :Descricao %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agendamentos/edit.html.erb
<center><h1>Editando Agendamento</h1>
<%= render 'form' %>

<%= link_to 'Abrir', @agendamento %> |
<%= link_to 'Voltar', agendamentos_path %>
</center>

app/views/agendamentos/index.html.erb
<div id="calendar">
  <h2 id="month">
    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
  </h2>
  <%= calendar_for @agendamentos, :year => @date.year, :month => @date.month do |t| %>
  <%= t.head('Domingo','Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado') %>
  <%= t.day do |day, agendamentos| %>
  <%= day.day %>
  <% agendamentos.each do |agendamento| %><br>
  <%= link_to h(agendamento.Nome), agendamento %><br>
  <% end %>
  <% end %>
  <% end %>
</div>
<center>

<h3><%= link_to "Novo agendamento", new_agendamento_path %></h3> 
</center>

app/views/agendamentos/new.html.erb
<center><h1>Novo Agendamento</h1>

<%= render 'form' %>


<div class="btn-group">
<h3><%= link_to "Voltar", agendamentos_path, :class => "btn" %></h3> 
</div>
</center>

app/views/agendamentos/show.html.erb
<center><p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @agendamento.Nome %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @agendamento.Descricao %>
</p>

<p>
  <strong>Data:</strong>
  <%= @agendamento.date %>
</p>

<%= link_to 'Editar', edit_agendamento_path(@agendamento) %> | <%= link_to 'Deletar', @agendamento, method: :delete, data: { confirm: 'O senhor(a) tem certeza?' } %> | <%= link_to 'Voltar', agendamentos_path %>
</center>

app/views/cadastros/_form.html.erb
<%= form_for @cadastro, :html => { :class => "form-horizontal cadastro" } do |f| %>

    <% if @cadastro.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cadastro.errors.count, "error") %> prohibited this cadastro from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cadastro.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%= error_span(@cadastro[:nome]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@cadastro[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :telefone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%= error_span(@cadastro[:telefone]) %>
  </div>
  <div class="control-group">
    <%= f.label :celular, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :celular, :class => 'form-control' %>
    </div>
    <%= error_span(@cadastro[:celular]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cadastros_path, :class => 'btn btn-default' %>

<% end %>

app/views/cadastros/edit.html.erb
<%- model_class = Cadastro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cadastros/index.html.erb
<%- model_class = Cadastro -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag(cadastros_path, :method => :get) do %>
<%= text_field_tag 'search', nil, placeholder: 'Pesquise o cliente aqui...' %>
<%= submit_tag "Pesquisar" %>
<% end %>


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:celular) %></th>
      <th><%= model_class.human_attribute_name(:criado_em) %></th>
      <th><%=t '.actions', :default => t("helpers.Ações") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cadastros.each do |cadastro| %>
      <tr>
        <td><%= link_to cadastro.id, cadastro_path(cadastro) %></td>
        <td><%= cadastro.nome %></td>
        <td><%= cadastro.email %></td>
        <td><%= cadastro.telefone %></td>
        <td><%= cadastro.celular %></td>
        <td><%=l cadastro.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.Editar")),
                      edit_cadastro_path(cadastro), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.Excluir")),
                      cadastro_path(cadastro),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'O senhor(a) tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.Novo")),
            new_cadastro_path,
            :class => 'btn btn-primary' %>

app/views/cadastros/new.html.erb
<%- model_class = Cadastro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cadastros/show.html.erb
<%- model_class = Cadastro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @cadastro.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @cadastro.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @cadastro.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:celular) %>:</strong></dt>
  <dd><%= @cadastro.celular %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.Voltar")),
              cadastros_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.Editar")),
              edit_cadastro_path(@cadastro), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.Excluir")),
              cadastro_path(@cadastro),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.Comfirmar", :default => 'O senhor(a) tem certeza?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Salão" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Salão</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Cadastro", cadastros_path %></li>
            <li><%= link_to "Agendamento",  agendamentos_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-25">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<% if admin_signed_in?%>
<br><br><br>
<center><h1>Bem vindo, <%= current_admin.email %></h1></center>
<br><br><br><br><hr>
 
	<ul>
		<center><h4>Se desejar se deslogar aperte em sair:</h4></center>
		<center><h2><%=button_to "Sair", destroy_admin_session_path, :method => :delete, :class=>"btn-warning"%></h2></center>
	</ul>
<% else %>
<div id ="login">
	<ul>
		<br><br><br>
		<center><h1>Bem vindo!!!</h1></center>
		<br><br><br><br><hr>

		<center><h4>Se já estiver cadastrado, por favor faça o login</h4></center>
		<center><h3><%=link_to "Logar", new_admin_session_path %></h3></center>
		<br><hr><br>
		<center><h4>Caso contrário, cadastre um novo adiministrador</h4></center>
		<center><h3><%=link_to "Cadastro de novo Admin", new_admin_session_path %></h3></center>
		<br><br>
		<hr>
	</ul>
</div>
<% end %>